server:
  port: 8081
  servlet:
    context-path: /app-one

security:
  oauth2:
    client:
      client-id: app-one
      client-secret: app-one-parak
      user-authorization-uri: http://127.0.0.1:8080/server/oauth/authorize
      access-token-uri: http://127.0.0.1:8080/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/server/oauth/token_key
