server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: CustomAuthenticationApplication
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/web?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: KAG1823

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: top.parak.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
